from datetime import datetime


def build_report(title: str, url: str, analysis: dict) -> str:
    """Build a markdown report from multi-agent analysis results."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    sections = [
        f"# {title}",
        "",
        f"**Source:** [{url}]({url})  ",
        f"**Analyzed:** {now}  ",
        "**Pipeline:** Summarizer > Insights Extractor > Risk Assessor > Scenario Predictor",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        analysis["summary"],
        "",
        "---",
        "",
        "## Market Insights",
        "",
        analysis["insights"],
        "",
        "---",
        "",
        "## Risk Assessment",
        "",
        analysis["risk_assessment"],
        "",
        "---",
        "",
        "## Predictive Scenarios",
        "",
        analysis["scenarios"],
        "",
        "---",
        "",
        (
            f"*Report generated by "
            f"[Article-Summary-Insights](https://github.com/Mohit1053/Article-Summary-Insights)"
            f" on {now}*"
        ),
    ]

    return "\n".join(sections) + "\n"
